### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by jeroensmeets** [comment]
First change is not an error, I wrote 'her' for a reason.

Second change is not clear.

**Comment by deavmi** [comment]
Why is it `her`? DO you grammar?

**Comment by jeroensmeets** [comment]
Hi Tristan, I checked and think that

`but everyone can start her own server`

`but everyone can start his own server`

`but everyone can start their own server`

are all grammatically correct. I prefer `her` to not automatically assume an instance owner is male.

**Comment by deavmi** [comment]
Their is better. Can be female or male.

This is the most PC; using her puts superiority on females. Their is neutral.

**Comment by jeroensmeets** [comment]
Hi Tristan, well we obviously disagree about what it means to use the word `her`. Pointing out superiority is not my intention, and I don't think it does so. For me it's a counterweight to the usual `hey guys` language in our technical community. Personally, I loved the diversity in presenters for the last Google IO.

As `his` wouldn't cause this type of discussion, my decision is to keep `her`.

**Comment by deavmi** [comment]
Okay. I can understand. It was nice debating with you. :)

**Pull request closed without merging**
